### ISSUE TITLE
Создать команды

### ISSUE THREAD

**Issue by PavelBahBah** [PavelBahBah/simbirsoft_cybersport#12]
Создать сущность команды. Поля:
Название
Дата создания
Список игроков (используем сущность игрока)

Добавить по аналогии с остальными сущностями страничку со списком команд и с каждой командой по отдельности.

**Comment by Soronkkk** [comment]
Pull Request для issue 12 : https://github.com/PavelBahBah/simbirsoft_cybersport/pull/14
