### ISSUE TITLE
Динамическое состояние шапки

### ISSUE THREAD

**Issue by PavelBahBah** [PavelBahBah/simbirsoft_cybersport#21]
Сделать динамическое состояние шапки. Если пользователь авторизован, то в шапке должны быть ссылки (их, кстати, надо сделать валидными, сейчас они пока никуда не ведут) на страницы "Новости", "Игроки", "Матчи", "Турниры", "Выйти". Если пользователь не авторизован, то должна быть только одна кнопка - "Войти".
Сделать их единообразными, в виде простых ссылок.

**Comment by Seri4** [comment]
Pull Request для cs-21: #27
