### ISSUE TITLE
Создать страницы "Профиль" и "Настройки".

### ISSUE THREAD

**Issue by PavelBahBah** [PavelBahBah/simbirsoft_cybersport#22]
Сверстать страницу профиля юзера. 
На данном этапе на ней должны находится никнейм, заглушка под аватар, кнопка "изменить аватар", открывающая форму загрузки картинки (пускай она ничего пока не делает), заглушка под "лычки", пустые блоки "публикации" и "комментарии", ссылку на настройки.

Сверстать страницу настроек юзера.
В ней сделать все как нарисовано в дизигне, но пока логику на бэке не реализовывать.

**Comment by Soronkkk** [comment]
Pull Request для cs-22: https://github.com/PavelBahBah/simbirsoft_cybersport/pull/25
