### ISSUE TITLE
Добавить регистрацию и форму восстановления пароля

### ISSUE THREAD

**Issue by PavelBahBah** [PavelBahBah/simbirsoft_cybersport#28]
Добавить страницу регистрации и страницу "забыл пароль". 
Страница регистрации должна содержать форму с логином, почтой и паролем. 
Страница "забыл пароль" должна содержать поле "почта" и кнопку "восстановить". 
Реализацию восстановления пароля пока не делать.
Ссылки на эти страницы тоже пока никуда не вставлять.

**Comment by Seri4** [comment]
Pull Request для cs-28: #29

**Comment by Seri4** [comment]
Пофиксил Pull Request для cs-28: #29
