### ISSUE TITLE
Сверстать страничку логина

### ISSUE THREAD

**Issue by PavelBahBah** [PavelBahBah/simbirsoft_cybersport#40]
Сверстать красивую и богатую страничку логина. 
Содержимое: поле логина, поле пароля, кнопочка "войти", ссылочка "забыл пароль".
Сделать в фирменных цветах нашего портала.

**Comment by Soronkkk** [comment]
Pull Request для CS-40: https://github.com/PavelBahBah/simbirsoft_cybersport/pull/43
