### ISSUE TITLE
Добавить комментарии

### ISSUE THREAD

**Issue by PavelBahBah** [PavelBahBah/simbirsoft_cybersport#45]
Добавить сущность комментария. Среди полей: айди, текст, автор, дата и время.
Добавить отображение комментариев под новостями.
Добавить форму добавления комментария для заголиненных юзеров.

**Comment by Soronkkk** [comment]
PullRequest для cs-45 : https://github.com/PavelBahBah/simbirsoft_cybersport/pull/48

**Comment by Soronkkk** [comment]
Новый PullRequest для cs-45 (ветка feuture/cs-45 переименована на feature/cs-45) :https://github.com/PavelBahBah/simbirsoft_cybersport/pull/53
