### ISSUE TITLE
Подготовить фрагмент для блока "прямой эфир"

### ISSUE THREAD

**Issue by PavelBahBah** [PavelBahBah/simbirsoft_cybersport#54]
Подготовить thymeleaf-фрагмент (на манер header) для блока прямой эфир. На текущем этапе это должна быть боковая колонка с моками секций прямого эфира. Эти секции представляют из себя по факту обычные комментарии пользователей. Т.е. в каждой секции должны содержаться аватарка, ник пользователя и комментарий.
Добавить на страничку с новостями этот блок, проверить что все выглядит аккуратно.

**Comment by Soronkkk** [comment]
PullRequest для cs-54: https://github.com/PavelBahBah/simbirsoft_cybersport/pull/55
