### ISSUE TITLE
Проектирование открытого REST API

### ISSUE THREAD

**Issue by PavelBahBah** [PavelBahBah/simbirsoft_cybersport#59]
Спроектировать, описать в wiki (в рамках этого проекта) и реализовать открытое REST API. 
Поддержать все, что можно безопасно отдавать анонимному пользователю (новости с комментами, игроки, команды, матчи, турниры). Лучше делать в отдельном пакете внутри пакета "controller.
В рамках этой же задачи поправить конфиги и добавить анонимным пользователям возможность смотреть сайт.

**Comment by Soronkkk** [comment]
PullRequest для cs-59: https://github.com/PavelBahBah/simbirsoft_cybersport/pull/61

Написанная wiki для cs-59:  https://github.com/PavelBahBah/simbirsoft_cybersport/wiki/REST-API-Documentation
