### ISSUE TITLE
Добавить страницу "матчи"

### ISSUE THREAD

**Issue by PavelBahBah** [PavelBahBah/simbirsoft_cybersport#65]
Реализовать страницу с матчами. У нас сейчас есть страница "команды" (/teams) реализованная в виде списка. В дальнейшем команды будут выглядеть как игроки, а вот матчи как раз таки должны выглядеть как эти списки. 
Сущность уже есть, нужно просто добавить отображение на фронте.

**Comment by Seri4** [comment]
PullRequest cs-65: #69
