### ISSUE TITLE
Добавить миграцию бд через liquibase.

### ISSUE THREAD

**Issue by PavelBahBah** [PavelBahBah/simbirsoft_cybersport#7]
Добавить и сконфигурировать liquibase. Создать несколько тестовых записей для тех сущностей, которые уже есть в проекте.

**Comment by Soronkkk** [comment]
Pull Request для issue 7 : https://github.com/PavelBahBah/simbirsoft_cybersport/pull/8

**Comment by PavelBahBah** [comment]
Поправил немного, а в целом все ок.
