### ISSUE TITLE
Добавить рейтинг

### ISSUE THREAD

**Issue by PavelBahBah** [PavelBahBah/simbirsoft_cybersport#85]
Добавить пользователю поле "рейтинг". В профиле поменять заглушку на отображение реального профиля. 
Добавить сущности "новость" поле "рейтинг". Под каждой новостью сделать цифру рейтинга с плюсом и минусом (как на моке).
Реализацию самого механизма лайка пока не делать.

**Comment by Seri4** [comment]
Pull Request cs-85: #87

**Comment by Seri4** [comment]
Pull Request cs-85: #91
